name: Deploy
on:
  push:
    tags: ['v*']
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Configure git author
        run: |
          git config --global user.name "github-actions-bot"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: npx gh-pages -d dist
